# Generated by Django 5.2.6 on 2025-09-04 05:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreateUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('lastn_name', models.CharField(max_length=50)),
                ('birthday', models.DateField()),
                ('age', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(18)])),
                ('city', models.CharField(max_length=50)),
                ('estate', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('live_mexico', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('number', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{9,15}$')])),
                ('charge', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('enterprise', models.CharField(max_length=30)),
                ('ubication', models.CharField(max_length=40)),
            ],
        ),
    ]
