# Generated by Django 5.2.6 on 2025-09-04 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tucampo_controller', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=30, unique=True)),
            ],
        ),
    ]
