# Generated by Django 5.2.6 on 2025-09-05 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tucampo_controller', '0002_login'),
    ]

    operations = [
        migrations.RenameField(
            model_name='createuser',
            old_name='lastn_name',
            new_name='last_name',
        ),
    ]
